# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0001_initial'),
    ]

    operations = [
    ]
