# Generated by Django 2.0 on 2018-07-25 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 15, 39, 50, 30281)),
        ),
    ]
