# Generated by Django 2.0 on 2018-07-25 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0002_auto_20180725_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 15, 44, 12, 111673)),
        ),
    ]
