# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0003_auto_20170522_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'login_customer',
            },
        ),
        migrations.CreateModel(
            name='DishReplacementSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietplan_food_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.GeneratedDietPlanFoodDetails')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Food')),
            ],
        ),
    ]
