# Generated by Django 2.0 on 2018-07-25 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0004_auto_20180725_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 15, 51, 45, 762365)),
        ),
    ]
