# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0004_dishreplacementsuggestions_logincustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishreplacementsuggestions',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
