# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0005_dishreplacementsuggestions_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFoodExclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('lamb_mutton', 'Lamb'), ('seafood', 'Seafood'), ('nuts', 'nuts'), ('wheat', 'wheat'), ('dairy', 'dairy'), ('POULTARY', 'poultary'), ('egg', 'egg')], max_length=100)),
            ],
            options={
                'db_table': 'erp_customer_food_exclusion',
            },
        ),
        migrations.CreateModel(
            name='CustomerMedicalConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'erp_customer_medicalcondition',
            },
        ),
        migrations.RemoveField(
            model_name='dishreplacementsuggestions',
            name='created_on',
        ),
    ]
