# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0006_auto_20170603_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'relation_log',
            },
        ),
        migrations.CreateModel(
            name='CustomerWeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('weight_type', models.IntegerField()),
            ],
            options={
                'db_table': 'erp_customer_weight_timeline',
            },
        ),
        migrations.CreateModel(
            name='ExerciseDietRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_level', models.CharField(max_length=150)),
                ('fit_level', models.CharField(max_length=150)),
                ('new_act_lavel', models.CharField(max_length=150)),
                ('preiodise', models.IntegerField()),
                ('uppercut', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'relation_ep_dp',
            },
        ),
        migrations.CreateModel(
            name='FoodTypeSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'food_type_sizes',
            },
        ),
        migrations.CreateModel(
            name='CustomerWaterLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer' ,db_column="user_id")),
            ],
        ),
        migrations.CreateModel(
            name='WaterContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bottle', 'Bottle'), ('glass', 'Glass')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dishreplacementsuggestions',
            name='dietplan_food_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='epilogue.GeneratedDietPlanFoodDetails'),
        ),
        migrations.AddField(
            model_name='customerwaterlogs',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.WaterContainer'),
        ),
        migrations.AddField(
            model_name='customerwaterlogs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
    ]
