# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0007_auto_20170812_0930'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerwaterlogs',
            index=models.Index(fields=['user_id'], name='epilogue_cu_custome_23b50a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerwaterlogs',
            index=models.Index(fields=['container'], name='epilogue_cu_contain_cebfe3_idx'),
        ),
    ]
