# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0008_auto_20170812_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSleepLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('saved', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_sleep_logs',
            },
        ),
        migrations.AddField(
            model_name='customerwaterlogs',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customerwaterlogs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='epilogue.Customer'),
        ),
    ]
