# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0009_auto_20170821_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivityLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('steps', models.IntegerField()),
                ('cals', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('distance', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='epilogue.Customer')),
            ],
        ),
    ]
