# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0010_customeractivitylogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivitylogs',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='epilogue.Customer'),
        ),
    ]
