# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0011_auto_20170824_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivitylogs',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
