# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0007_auto_20170828_1247'),
        ('epilogue', '0012_auto_20170824_2146'),
    ]

    operations = [
    ]
