# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0013_merge_20170913_1530'),
    ]

    operations = [
    ]
