# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0013_merge_20170913_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'erp_customer_level_log',
            },
        ),
        migrations.CreateModel(
            name='CustomerReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylevellog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='businesscustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerfoodexclusions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customermedicalconditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customersleeplogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerweightrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisedietrelation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foodtypesizes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generateddietplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generateddietplanfooddetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generatedexerciseplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logincustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={},
        ),
        migrations.AddField(
            model_name='customerreasons',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='customerreasons',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Reasons'),
        ),
        migrations.AddField(
            model_name='customerlevellog',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to='epilogue.Customer'),
        ),
    ]
