# Generated by Django 2.0 on 2018-01-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0014_auto_20180105_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivitylogs',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='customerreasons',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='customerreasons',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Reasons'),
        ),
        migrations.AlterField(
            model_name='generateddietplan',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
