# Generated by Django 2.0 on 2017-12-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0014_customerlevellog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylevellog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='businesscustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerfoodexclusions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customermedicalconditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customersleeplogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerweightrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisedietrelation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foodtypesizes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generateddietplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generateddietplanfooddetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generatedexerciseplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logincustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={},
        ),
        migrations.AlterField(
            model_name='customerwaterlogs',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.WaterContainer'),
        ),
        migrations.AlterField(
            model_name='dishreplacementsuggestions',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Food'),
        ),
    ]
