# Generated by Django 2.0 on 2017-12-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0015_auto_20171219_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevellog',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitylevel_logs', to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='body_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='food_cat',
            field=models.CharField(blank=True, choices=[('veg', 'veg'), ('nonveg', 'nonveg'), ('egg', 'egg')], max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='h_type',
            field=models.IntegerField(db_column='height_type', default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='objective',
            field=models.ForeignKey(blank=True, db_column='objective', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Objective'),
        ),
        migrations.AddField(
            model_name='customer',
            name='w_type',
            field=models.IntegerField(db_column='weight_type', default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='work_pref',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customerfoodexclusions',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='customermedicalconditions',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='customersleeplogs',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='customerweightrecord',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='food',
            name='beef',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='grains_cereals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='lamb_mutton',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='non_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='non_veg_gravy_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='nut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='other_meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='pork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='poultary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='pulse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='seafood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='squared_diff_weight_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='squared_diff_weight_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='squared_diff_weight_maintain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='vegetables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitaminc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='wheat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generateddietplan',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietplans', to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='generateddietplan',
            name='year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='dietplan',
            field=models.ForeignKey(db_column='erp_diet_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='epilogue.GeneratedDietPlan'),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='food_item',
            field=models.ForeignKey(db_column='business_diet_list_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Food'),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='food_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generateddietplanfooddetails',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generatedexerciseplan',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='generatedexerciseplan',
            name='glo_level_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logincustomer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logincustomer',
            name='customer',
            field=models.OneToOneField(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
        migrations.AddField(
            model_name='logincustomer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logincustomer',
            name='status_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gen',
            field=models.CharField(blank=True, db_column='gender', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='h',
            field=models.CharField(blank=True, db_column='height', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ls',
            field=models.CharField(blank=True, db_column='lifestyle', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='w',
            field=models.CharField(blank=True, db_column='weight', max_length=11),
        ),
        migrations.AlterField(
            model_name='customeractivitylogs',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='customerfoodexclusions',
            name='food_type',
            field=models.CharField(choices=[('lamb_mutton', 'Lamb'), ('seafood', 'Seafood'), ('nuts', 'nuts'), ('wheat', 'wheat'), ('dairy', 'dairy'), ('poultary', 'poultary'), ('egg', 'egg'), ('beef', 'beef'), ('meat', 'meat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customersleeplogs',
            name='minutes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerwaterlogs',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.WaterContainer'),
        ),
        migrations.AlterField(
            model_name='customerwaterlogs',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='dishreplacementsuggestions',
            name='dietplan_food_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='epilogue.GeneratedDietPlanFoodDetails'),
        ),
        migrations.AlterField(
            model_name='dishreplacementsuggestions',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='cereal_grains',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='dairy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='dessert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='drink',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='for_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fruit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m5_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m5_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='m5_stable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='nuts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='pulses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='salad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='snaks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='vegetable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='yogurt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='calorie',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='food_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='meal_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logincustomer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logincustomer',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
