# Generated by Django 2.0 on 2018-01-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0016_auto_20171219_1716'),
        ('epilogue', '0015_auto_20180109_1801'),
    ]

    operations = [
    ]
