# Generated by Django 2.0 on 2017-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0016_auto_20171219_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to='epilogue.Customer')),
            ],
            options={
                'db_table': 'erp_customer_level_log',
            },
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=3),
        ),
    ]
