# Generated by Django 2.0 on 2018-01-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0017_merge_20180109_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitylevel_logs', to='epilogue.Customer'),
        ),
    ]
