# Generated by Django 2.0 on 2018-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0018_auto_20180109_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=6),
        ),
    ]
