# Generated by Django 2.0 on 2018-01-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0019_auto_20180113_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='h',
            field=models.IntegerField(blank=True, db_column='height', default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='w',
            field=models.IntegerField(db_column='weight', default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='customerlevellog',
            name='customer',
            field=models.ForeignKey(db_column='erp_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=3),
        ),
    ]
