# Generated by Django 2.0 on 2018-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0020_auto_20180117_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='h',
            field=models.IntegerField(db_column='height', default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='w',
            field=models.IntegerField(db_column='weight', default=0),
        ),
    ]
