# Generated by Django 2.0 on 2018-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0021_auto_20180117_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='h',
            field=models.CharField(db_column='height', default='0.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='w',
            field=models.CharField(db_column='weight', default='0.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=4),
        ),
    ]
