# Generated by Django 2.0 on 2018-01-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0022_auto_20180118_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='objective',
            field=models.ForeignKey(db_column='objective', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Objective'),
        ),
    ]
