# Generated by Django 2.0.1 on 2018-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0023_auto_20180118_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gen',
            field=models.CharField(blank=True, db_column='gender', default='female', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeractivitylogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=5),
        ),
    ]
