# Generated by Django 2.0.1 on 2018-03-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0024_auto_20180216_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=6),
        ),
    ]
