# Generated by Django 2.0.1 on 2018-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0025_auto_20180317_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
