# Generated by Django 2.0 on 2018-04-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0026_auto_20180319_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=4),
        ),
    ]
