# Generated by Django 2.0 on 2018-04-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0027_auto_20180405_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=5),
        ),
    ]
