# Generated by Django 2.0 on 2018-04-09 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0028_auto_20180406_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevellog',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 8, 44, 49, 635597)),
        ),
        migrations.AddField(
            model_name='activitylevellog',
            name='week',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='activitylevellog',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
