# Generated by Django 2.0 on 2018-05-04 10:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0030_auto_20180502_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 15, 30, 0, 909681)),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=5),
        ),
    ]
