# Generated by Django 2.0 on 2018-05-05 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0031_auto_20180504_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddietplan',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 15, 47, 42, 46675)),
        ),
        migrations.AlterField(
            model_name='customerfooditemspreference',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preference', to='epilogue.Customer'),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=6),
        ),
    ]
