# Generated by Django 2.0 on 2018-06-07 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0032_auto_20180505_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDietPlanFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('followed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customerdietplanfollow',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilogue.Customer'),
        ),
    ]
