# Generated by Django 2.0 on 2018-06-07 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0033_auto_20180607_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevellog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 13, 39, 27, 903358)),
        ),
        migrations.AlterField(
            model_name='activitylevellog',
            name='week',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gen',
            field=models.CharField(blank=True, db_column='gender', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='objective',
            field=models.ForeignKey(db_column='objective', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='epilogue.Objective'),
        ),
        migrations.AlterField(
            model_name='generateddietplanfooddetails',
            name='day',
            field=models.IntegerField(default=4),
        ),
       migrations.AddIndex(
            model_name='customerdietplanfollow',
            index=models.Index(fields=['customer', '-day', '-week', '-year'], name='epilogue_cu_custome_d7d8f8_idx'),
        ),
    ]
