# Generated by Django 2.0 on 2018-06-07 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0034_auto_20180607_1339'),
    ]

    operations = [
       migrations.AlterUniqueTogether(
            name='customerdietplanfollow',
            unique_together={('customer', 'day', 'week', 'year', 'followed')},
        ),
   ]
