# Generated by Django 2.0 on 2018-06-16 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0035_auto_20180607_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDietFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('type', models.IntegerField(choices=[(0, 'item'), (1, 'meal'), (2, 'day')])),
                ('meal', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Mid Day Snack'), (3, 'Lunch'), (4, 'Evening Snack'), (5, 'Dinner')])),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='epilogue.Customer')),
                ('foods', models.ManyToManyField(to='epilogue.Food')),
            ],
        ),
   ]
