# Generated by Django 2.0 on 2018-06-23 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0036_auto_20180623_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietfavouritefoods',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0),
        ),

    ]
