# Generated by Django 2.0 on 2018-01-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epilogue', '0018_auto_20180109_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegenerationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('type', models.CharField(choices=[('diet', 'Diet'), ('workout', 'Workout')], max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('regenerated_on', models.DateTimeField(auto_now=True)),
                ('regenerated', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regeneration_nodes', to='epilogue.Customer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regenerationlog',
            unique_together={('customer', 'year', 'week')},
        ),
        migrations.AlterIndexTogether(
            name='regenerationlog',
            index_together={('customer', 'year', 'week')},
        ),
    ]
