# Generated by Django 2.0 on 2018-01-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0020_auto_20180117_1954'),
        ('regeneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regenerationlog',
            unique_together={('customer', 'year', 'week', 'type')},
        ),
        migrations.AlterIndexTogether(
            name='regenerationlog',
            index_together={('customer', 'year', 'week', 'type')},
        ),
    ]
