# Generated by Django 2.0 on 2017-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0017_auto_20171220_1547'),
        ('regeneration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regenerationlog',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regeneration_nodes', to='epilogue.Customer'),
        ),
    ]
