# Generated by Django 2.0 on 2017-12-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0017_auto_20171220_1547'),
        ('regeneration', '0002_regenerationlog_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regenerationlog',
            unique_together={('customer', 'year', 'week')},
        ),
        migrations.AlterIndexTogether(
            name='regenerationlog',
            index_together={('customer', 'year', 'week')},
        ),
    ]
