# Generated by Django 2.0 on 2017-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regeneration', '0003_auto_20171220_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='regenerationlog',
            name='regenerated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='regenerationlog',
            name='regenerated',
            field=models.BooleanField(default=False),
        ),
    ]
