# Generated by Django 2.0 on 2018-07-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epilogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGoogleClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.DateTimeField(auto_now_add=True)),
                ('clientId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('clientId', models.CharField(max_length=255)),
                ('visited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPageTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('gaclient', models.CharField(max_length=255)),
                ('referralId', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignupSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('campaign', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(default='english', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupsource', to='epilogue.Customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['email'], name='analytics_u_email_2feef4_idx'),
        ),
        migrations.AddField(
            model_name='customergoogleclient',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaclientids', to='epilogue.Customer'),
        ),
        migrations.AddIndex(
            model_name='customergoogleclient',
            index=models.Index(fields=['customer'], name='analytics_c_custome_d753dc_idx'),
        ),
        migrations.AddIndex(
            model_name='customergoogleclient',
            index=models.Index(fields=['clientId'], name='analytics_c_clientI_549452_idx'),
        ),
        migrations.AddIndex(
            model_name='customergoogleclient',
            index=models.Index(fields=['customer', 'clientId'], name='analytics_c_custome_3273bc_idx'),
        ),
    ]
