# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('gaclient', models.CharField(max_length=255)),
                ('referralId', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
            ],
        ),
    ]
