# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_eventpagetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpagetracking',
            name='referralId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
