# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170908_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavratriUserEmailSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
