# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0013_merge_20170913_1530'),
        ('analytics', '0004_navratriuseremailsharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('campaign', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupsource', to='epilogue.Customer')),
            ],
        ),
    ]
