# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_delete_navratriuseremailsharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpagetracking',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
