# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_eventpagetracking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupsource',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
