# Generated by Django 2.0 on 2018-04-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_usersignupsource_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['email'], name='analytics_u_email_2feef4_idx'),
        ),
    ]
