# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardioFloorExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=250, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('swing1', models.CharField(blank=True, max_length=10, null=True)),
                ('home', models.CharField(blank=True, max_length=10, null=True)),
                ('gym', models.CharField(blank=True, max_length=10, null=True)),
                ('machine_required', models.CharField(blank=True, max_length=10, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=250, null=True)),
                ('exercise_level', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=250, null=True)),
                ('swing_field', models.BooleanField()),
                ('home_field', models.BooleanField()),
                ('gym_field', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CardioTimeBasedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.CharField(blank=True, max_length=250, null=True)),
                ('home', models.CharField(blank=True, max_length=10, null=True)),
                ('gym', models.CharField(blank=True, max_length=10, null=True)),
                ('machine_required', models.CharField(blank=True, max_length=10, null=True)),
                ('machine_required_home', models.CharField(blank=True, max_length=250, null=True)),
                ('machine_required_gym', models.CharField(blank=True, max_length=250, null=True)),
                ('exercise_level', models.CharField(blank=True, max_length=50, null=True)),
                ('functional_warmup', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoviceCoreStrengthiningExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=250)),
                ('reps', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('hold', models.CharField(max_length=10)),
                ('swing1', models.CharField(max_length=10)),
                ('rotation', models.CharField(max_length=10)),
                ('swing2', models.CharField(max_length=10)),
                ('sets', models.IntegerField()),
                ('home', models.CharField(max_length=50)),
                ('gym', models.CharField(max_length=50)),
                ('machine_required', models.CharField(max_length=10)),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_level', models.CharField(blank=True, max_length=100, null=True)),
                ('muscle_group_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('muscle_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('body_part', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTrainingExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('exercise_group', models.CharField(max_length=30)),
                ('left_right', models.BooleanField()),
                ('home', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('eqip_name_home', models.CharField(max_length=100)),
                ('machine_required', models.BooleanField()),
                ('machine_name', models.CharField(max_length=100)),
                ('exercise_level', models.CharField(max_length=10)),
                ('muscle_group_cat', models.CharField(max_length=100)),
                ('sub_muscle_group', models.CharField(max_length=30)),
                ('body_part', models.CharField(max_length=30)),
                ('exercise_type', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StretchingExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=250, null=True)),
                ('swing1', models.BooleanField()),
                ('home', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('machine_required', models.BooleanField()),
                ('machine_name', models.CharField(blank=True, max_length=250, null=True)),
                ('muscle_group_cat', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_muscle_group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('muscle_group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('body_part', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
