# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupCoolDownMobilityDrillExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('swing1', models.BooleanField()),
                ('home', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('machine_required', models.BooleanField()),
                ('machine_name', models.CharField(max_length=100)),
                ('exercise_level', models.CharField(max_length=30)),
                ('joint_name', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=50)),
                ('muscle_group_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WarmupCoolDownTimeBasedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('time_unit', models.IntegerField()),
                ('machine_required', models.BooleanField()),
                ('machine_name', models.CharField(max_length=100)),
                ('exercise_level', models.CharField(max_length=30)),
                ('muscle_group', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('home', models.BooleanField()),
                ('gym', models.BooleanField()),
            ],
        ),
    ]
