# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warmupcooldowntimebasedexercise',
            name='time_unit',
            field=models.CharField(default='secs', max_length=10),
        ),
    ]
