# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_warmupcooldownmobilitydrillexercise_warmupcooldowntimebasedexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiofloorexercise',
            name='gym_field',
        ),
        migrations.RemoveField(
            model_name='cardiofloorexercise',
            name='home_field',
        ),
        migrations.RemoveField(
            model_name='cardiofloorexercise',
            name='swing_field',
        ),
    ]
