# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20170816_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='duration',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
