# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20170815_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='gym',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='machine_required',
            field=models.BooleanField(default=True),
        ),
    ]
