# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('workout', '0004_auto_20171024_1738'), ('workout', '0005_auto_20171024_1738'), ('workout', '0006_auto_20171024_1738')]

    dependencies = [
        ('workout', '0003_auto_20171003_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiotimebasedexercise',
            name='duration',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cardiotimebasedexercise',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
