# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20171024_1738_squashed_0006_auto_20171024_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_name', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(db_column='erp_customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='epilogue.Customer')),
            ],
            options={
                'db_table': 'erp_customer_injury',
            },
        ),
        migrations.CreateModel(
            name='GeneratedExercisePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('user_week_id', models.IntegerField()),
                ('week_id', models.IntegerField()),
                ('customer', models.ForeignKey(db_column='erp_customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='epilogue.Customer')),
            ],
            options={
                'db_table': 'erp_exercise_plan',
            },
        ),
        migrations.CreateModel(
            name='GeneratedExercisePlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('exercise_type', models.IntegerField()),
                ('workout_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
                ('sets', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=50)),
                ('equipment_name', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=100)),
                ('mod_name', models.CharField(max_length=30)),
                ('mod_id', models.IntegerField()),
                ('workoutplan', models.ForeignKey(db_column='erp_exercise_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.GeneratedExercisePlan')),
            ],
            options={
                'db_table': 'erp_exercise_plan_detail',
            },
        ),
        migrations.RemoveField(
            model_name='cardiofloorexercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='novicecorestrengthiningexercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='warmupcooldownmobilitydrillexercise',
            name='duration',
        ),
        migrations.AddField(
            model_name='cardiofloorexercise',
            name='_duration',
            field=models.IntegerField(db_column='duration', default=0),
        ),
        migrations.AddField(
            model_name='novicecorestrengthiningexercise',
            name='_duration',
            field=models.IntegerField(db_column='duration', default=0),
        ),
        migrations.AddField(
            model_name='warmupcooldownmobilitydrillexercise',
            name='_duration',
            field=models.IntegerField(db_column='duration', default=0),
        ),
    ]
