# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20170815_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiofloorexercise',
            name='swing1',
            field=models.BooleanField(default=True),
        ),
    ]
