# Generated by Django 2.0 on 2017-12-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_generatedexerciseplandetails_description'),
    ]

    operations = [
    ]
