# Generated by Django 2.0 on 2017-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_remove_generatedexerciseplandetails_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedexerciseplandetails',
            name='image_name',
        ),
    ]
