# Generated by Django 2.0 on 2018-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_remove_generatedexerciseplandetails_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexerciseplandetails',
            name='image',
            field=models.URLField(default='http://www.98fit.com/webroot/workout_images/workout_blank.jpg'),
        ),
    ]
