# Generated by Django 2.0.1 on 2018-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_generatedexerciseplandetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexerciseplan',
            name='glo_level_id',
            field=models.IntegerField(default=1),
        ),
    ]
