# Generated by Django 2.0.1 on 2018-03-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_generatedexerciseplan_glo_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedexerciseplan',
            name='glo_level_id',
        ),
        migrations.AddField(
            model_name='generatedexerciseplan',
            name='lifestyle',
            field=models.FloatField(default=1.2),
        ),
    ]
