# Generated by Django 2.0.1 on 2018-03-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_auto_20180316_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedexerciseplan',
            name='lifestyle',
            field=models.FloatField(db_column='life_style', default=1.2),
        ),
    ]
