# Generated by Django 2.0.1 on 2018-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_auto_20180317_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexerciseplan',
            name='level',
            field=models.IntegerField(db_column='glo_level_id', default=1),
        ),
    ]
