# Generated by Django 2.0 on 2018-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
