# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20170919_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstracking',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
