# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20170919_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstracking',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
